import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from PIL import Image
from glob import glob

from astropy.time import Time
from astroquery.jplhorizons import Horizons

os.makedirs("2D_visualization", exist_ok=True)

ALPHA = pd.read_csv("./ALPHA.csv")
BETA = pd.read_csv("./BETA.csv")

# =========================
# EXTRACT DATA
# =========================

Ax = ALPHA["x"].to_numpy()
Ay = ALPHA["y"].to_numpy()
Az = ALPHA["z"].to_numpy()

Bx = BETA["x"].to_numpy()
By = BETA["y"].to_numpy()
Bz = BETA["z"].to_numpy()

NA = len(ALPHA["Time"].to_numpy())
NB = len(BETA["Time"].to_numpy())

if NA > NB:
    N = NB
    T = BETA["Time"].to_numpy()
else:
    N = NA
    T = ALPHA["Time"].to_numpy()

print("Creating individual images might take a while...")
print("Please wait....")


# Plot limits
limit = 110

fig, ax = plt.subplots(1, 2, figsize=(12, 6))

for i in range(N):

    if i > 0:

        # XY plane trails
        ax[0].plot(
            Ax[:i], Ay[:i],
            color='green',
            alpha=0.6,
            linewidth=1
        )

        ax[0].plot(
            Bx[:i], By[:i],
            color='red',
            alpha=0.6,
            linewidth=1
        )

        # XZ plane trails
        ax[1].plot(
            Ax[:i], Az[:i],
            color='green',
            alpha=0.6,
            linewidth=1
        )

        ax[1].plot(
            Bx[:i], Bz[:i],
            color='red',
            alpha=0.6,
            linewidth=1
        )


    ax[0].scatter(
        Ax[i], Ay[i],
        color='green',
        s=80,
        label="ALPHA"
    )

    ax[1].scatter(
        Ax[i], Az[i],
        color='green',
        s=80,
        label="ALPHA"
    )

    ax[0].scatter(
        Bx[i], By[i],
        color='red',
        s=80,
        label="BETA"
    )

    ax[1].scatter(
        Bx[i], Bz[i],
        color='red',
        s=80,
        label="BETA"
    )

    ax[0].scatter(
        0, 0,
        color='yellow',
        s=250,
        edgecolors='orange',
        label="SUN"
    )

    ax[1].scatter(
        0, 0,
        color='yellow',
        s=250,
        edgecolors='orange',
        label="SUN"
    )

    ax[0].set_xlim(-limit, limit)
    ax[0].set_ylim(-limit, limit)

    ax[1].set_xlim(-limit, limit)
    ax[1].set_ylim(-limit, limit)

    ax[0].set_xlabel("x [au]")
    ax[0].set_ylabel("y [au]")

    ax[1].set_xlabel("x [au]")
    ax[1].set_ylabel("z [au]")

    ax[0].set_title("Top View (x-y plane)")
    ax[1].set_title("Side View (x-z plane)")

    ax[0].grid()
    ax[1].grid()

    ax[0].annotate(
        f"{T[i]:.1f} yrs",
        (-0.9 * limit, 0.85 * limit),
        fontsize=12
    )

    ax[1].legend(loc="upper right")

    plt.savefig(
        f"2D_visualization/Plot_{i+1:05d}.png",
        dpi=200,
        bbox_inches='tight'
    )

    ax[0].clear()
    ax[1].clear()

    if i % 20 == 0:
        print(f"Rendered frame {i}/{N}")

plt.close(fig)

print("Animation frames finished!")

# 1. Look for the images generated by your plotting script
# Make sure the folder 'visualization' is in the same directory as this script
path_pattern = '2D_visualization/Plot_*.png'
image_frames = sorted(glob(path_pattern))

if not image_frames:
    print(f"Error: No images found in '3D_visualization/' matching {path_pattern}")
    print("Make sure you ran your plotting script first!")
else:
    print(f"Found {len(image_frames)} frames. Starting GIF compilation...")

image_frames = sorted(glob('2D_visualization/Plot_*.png'))


def create_simulation_gif(image_frames, output_name='3D_3body_simulation.gif'):
    if not image_frames:
        print("No frames found to process.")
        return

    # 1. Define a generator to yield images one by one
    # This keeps only one image in RAM at a time during the save process
    def frame_generator():
        for filename in image_frames:
            # Using a 'with' statement ensures the file is closed after use
            with Image.open(filename) as img:
                # Convert to 'P' mode (palette) with fewer colors 
                # This makes the GIF much smaller and less likely to lag
                yield img.convert('RGB').convert('P', palette=Image.ADAPTIVE)

    # 2. Initialize the generator
    frames = frame_generator()
    
    # 3. Pull the first frame to act as the anchor
    try:
        first_frame = next(frames)
    except StopIteration:
        print("Frame list was empty.")
        return

    # 4. Save the GIF
    print(f"Starting GIF creation for {len(image_frames)} frames...")
    
    first_frame.save(
        output_name,
        save_all=True,
        append_images=frames,  # Pillow iterates through the generator here
        duration=100,          # 100ms = 10 frames per second
        loop=0,                # 0 = infinite loop
        optimize=True          # Compresses the palette for memory efficiency
    )

    print(f"Success! {output_name} has been created.")

# Example usage:
create_simulation_gif(image_frames)
