import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from PIL import Image
from glob import glob

from astropy.time import Time
from astroquery.jplhorizons import Horizons


ALPHA = pd.read_csv("./ALPHA.csv")
BETA = pd.read_csv("./BETA.csv")

# Create folder
os.makedirs("3D_visualization", exist_ok=True)

# Assuming ALPHA and BETA are your DataFrames from Mercury 6
NA = len(ALPHA["Time"].to_numpy())
NB = len(BETA["Time"].to_numpy())

if NA > NB:
    N = NB
    T = BETA["Time"].to_numpy()
else:
    N = NA
    T = ALPHA["Time"].to_numpy()

print("Creating individual images might take a while...")
print("Please wait....")

# Setup the figure for 3D
fig = plt.figure(figsize=(12, 10))
ax = fig.add_subplot(111, projection='3d')

limit = 110

for i in range(N):
    # 1. Clear the frame
    ax.clear()

    # 2. Re-plot the static SUN
    ax.scatter(0, 0, 0, color='yellow', s=200, edgecolors='orange', label="SUN")

    # 3. Plot the HISTORY (the path up to the current frame 'i')
    # Use slicing [:i] to show the "trail"
    if i > 0:
        ax.plot(ALPHA["x"][:i], ALPHA["y"][:i], ALPHA["z"][:i], color='green', alpha=0.6, linewidth=1)
        ax.plot(BETA["x"][:i], BETA["y"][:i], BETA["z"][:i], color='red', alpha=0.6, linewidth=1)

    # 4. Plot the CURRENT positions as glowing spheres
    ax.scatter(ALPHA["x"].iloc[i], ALPHA["y"].iloc[i], ALPHA["z"].iloc[i], color='green', s=80, label="ALPHA")
    ax.scatter(BETA["x"].iloc[i], BETA["y"].iloc[i], BETA["z"].iloc[i], color='red', s=80, label="BETA")

    # 5. Fixed Axis Limits (Crucial for animation stability)
    ax.set_xlim(limit, -limit)
    ax.set_ylim(limit, -limit)
    ax.set_zlim(-limit, limit)

    # 6. Labels and Title
    ax.set_xlabel('X [AU]')
    ax.set_ylabel('Y [AU]')
    ax.set_zlabel('Z [AU]')
    # Convert Time to years if it's in days
    current_yr = T[i] / 365.25 
    ax.set_title(f'3-Body Stellar Dynamics\nTime: {current_yr:.2f} Years')
    
    # Optional: Rotate the camera slightly every frame for a cool cinematic effect
    ax.view_init(elev=20, azim=45 + (i * 0.1)) 

    # 7. Save Frame
    plt.savefig(f"3D_visualization/Frame_{i:05d}.png", dpi=150)
    
    # Print progress every 100 frames so you know it hasn't crashed
    if i % 20 == 0:
        print(f"Rendered frame {i}/{N}")

plt.close(fig)
print("Animation frames finished!")

# 1. Look for the images generated by your plotting script
# Make sure the folder 'visualization' is in the same directory as this script
path_pattern = '3D_visualization/Frame_*.png'
image_frames = sorted(glob(path_pattern))


def create_simulation_gif(image_frames, output_name='3D_3body_simulation.gif'):
    if not image_frames:
        print("No frames found to process.")
        return

    # 1. Define a generator to yield images one by one
    # This keeps only one image in RAM at a time during the save process
    def frame_generator():
        for filename in image_frames:
            # Using a 'with' statement ensures the file is closed after use
            with Image.open(filename) as img:
                # Convert to 'P' mode (palette) with fewer colors 
                # This makes the GIF much smaller and less likely to lag
                yield img.convert('RGB').convert('P', palette=Image.ADAPTIVE)

    # 2. Initialize the generator
    frames = frame_generator()
    
    # 3. Pull the first frame to act as the anchor
    try:
        first_frame = next(frames)
    except StopIteration:
        print("Frame list was empty.")
        return

    # 4. Save the GIF
    print(f"Starting GIF creation for {len(image_frames)} frames...")
    
    first_frame.save(
        output_name,
        save_all=True,
        append_images=frames,  # Pillow iterates through the generator here
        duration=100,          # 100ms = 10 frames per second
        loop=0,                # 0 = infinite loop
        optimize=True          # Compresses the palette for memory efficiency
    )

    print(f"Success! {output_name} has been created.")

# Example usage:
create_simulation_gif(image_frames)
