import os
from glob import glob
from PIL import Image

# 1. Look for the images generated by your plotting script
# Make sure the folder 'visualization' is in the same directory as this script
path_pattern = 'visualization/Frame_*.png'
image_frames = sorted(glob(path_pattern))

# 2. Check if we actually found any images
if not image_frames:
    print(f"Error: No images found in 'visualization/' matching {path_pattern}")
    print("Make sure you ran your plotting script first!")
else:
    print(f"Found {len(image_frames)} frames. Starting GIF compilation...")
    
    images = []
    for filename in image_frames:
        img = Image.open(filename)
        images.append(img)

    # 3. Save as GIF using the first image as the base
    # We use images[0] as the anchor to avoid the IndexError
    output_name = '3_body_simulation.gif'
    
    images[0].save(
        output_name,
        save_all=True,
        append_images=images[1:], # Attach all other frames
        duration=100,             # ms per frame (lower is faster)
        loop=0,                   # 0 means infinite loop
        format='GIF'
    )

    print(f"Success! {output_name} has been created.")